stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/demo.test
    - src/preprocess.py
    outs:
    - data/processed/processed.txt
  train:
    cmd: python src/train.py
    deps:
    - data/processed/processed.txt
    - src/train.py
    outs:
    - models/model.txt
    metrics:
    - metrics.txt
